---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frext-compile-rabbit
  labels:
    app: frext-compile-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frext-compile-rabbit
  template:
    metadata:
      labels:
        app: frext-compile-rabbit
    spec:
      containers:
      - name: frext-compile-rabbit
        image: wxwd14388/frext-compile-rabbitmq:v0.1.1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frext-test-rabbit
  labels:
    app: frext-test-rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frext-test-rabbit
  template:
    metadata:
      labels:
        app: frext-test-rabbit
    spec:
      containers:
      - name: frext-test-rabbit
        image: wxwd14388/frext-test-rabbitmq:v0.1.2
