apiVersion: v1
kind: Service
metadata:
  name: frext-online-svc-outer
spec:
  type: NodePort
  selector:
    app: frext-online-test
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 8030
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: frext-online-svc
spec:
  selector:
    app: frext-online-test
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 8030

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frext-online-test
  labels:
    app: frext-online-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frext-online-test
  template:
    metadata:
      labels:
        app: frext-online-test
    spec:
      serviceAccountName:
        frext
      containers:
      - name: frext-online-test
        image: wxwd14388/frext-online-test:v0.9.0
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 4;done"]
        volumeMounts:
        - mountPath: /tmp/FrexT
          name: frext-job
        ports:
          - containerPort: 8030
      volumes:
        - name: frext-job
          hostPath:
            path: /mnt/hgfs/0Web
            type: Directory
