apiVersion: v1
kind: Service
metadata:
  name: frext-testing-svc-outer
spec:
  type: NodePort
  selector:
    app: frext-testing-test
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 8030
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: frext-testing-svc
spec:
  selector:
    app: frext-testing-test
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 8030

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frext-testing-test
  labels:
    app: frext-testing-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frext-testing-test
  template:
    metadata:
      labels:
        app: frext-testing-test
    spec:
      serviceAccountName:
        frext
      initContainers:
      - name: volume-mount-hack
        image: debian:stable-slim
        command: ["sh", "-c", "chown -R 1001:1001 /nexus"]
        volumeMounts:
        - name: fs
          mountPath: /nexus
      containers:
      - name: frext-testing-test
        image: wxwd14388/frext-testing:v1.0.0
        volumeMounts:
        - name: frext-job
          mountPath: /tmp/FrexT
        - name: fs
          mountPath: /data/FrexT
        ports:
          - containerPort: 8030
      volumes:
        - name: frext-job
          hostPath:
            path: /root/FrexT
            type: Directory
        - name: fs
          hostPath:
            path: /root/FrexT_data/frext-file-system/log_testing
            type: Directory
