# Generated by Django 3.0.5 on 2021-09-04 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('role', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin'), ('undefined', 'undefined')], max_length=10)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('logup_time', models.DateTimeField(auto_now_add=True)),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['logup_time'],
            },
        ),
    ]
