apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-svc-outer
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbit-mq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30567
