# Generated by Django 3.0.5 on 2021-09-04 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitList',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(choices=[('pass', 'pass'), ('try', 'try'), ('unknown', 'unknown')], max_length=8)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('status', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('result', models.TextField()),
                ('cycle', models.IntegerField(default=-1)),
                ('compile_start_time', models.DateTimeField()),
                ('compile_end_time', models.DateTimeField()),
                ('test_start_time', models.DateTimeField()),
                ('test_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestList',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('combination', 'combination'), ('time_sequence', 'time_sequence'), ('system_all', 'system_all'), ('undefined', 'undefined')], max_length=16)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submit_number', models.PositiveIntegerField(default=0)),
                ('pass_number', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(max_length=128, unique=True)),
                ('top_module_name', models.CharField(max_length=256)),
                ('author', models.CharField(default='admin', max_length=128)),
                ('email', models.CharField(default='21921088@zju.edu.cn', max_length=128)),
                ('company', models.CharField(default='ARClab', max_length=128)),
                ('visibility', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidSubmitList',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.SubmitList')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.TestList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.TestList')),
            ],
        ),
        migrations.AddField(
            model_name='submitlist',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.TestList'),
        ),
        migrations.AddField(
            model_name='submitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User'),
        ),
        migrations.CreateModel(
            name='BestSubmitList',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.SubmitList')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.TestList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
