# Generated by Django 3.0.5 on 2021-09-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210905_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitlist',
            name='compile_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitlist',
            name='compile_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitlist',
            name='test_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitlist',
            name='test_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
