# Generated by Django 3.0.5 on 2021-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210905_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitlist',
            name='state',
            field=models.CharField(choices=[('see', 'see'), ('pass', 'pass'), ('try', 'try'), ('unknown', 'unknown')], default='see', max_length=8),
        ),
    ]
