# Generated by Django 3.0.5 on 2021-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210908_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitlist',
            name='comTime',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='submitlist',
            name='exeTime',
            field=models.IntegerField(default=-1),
        ),
    ]
