# Generated by Django 3.0.5 on 2021-10-21 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_loginrecord'),
        ('Home', '0006_auto_20211009_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('login_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.LoginRecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
