# Generated by Django 3.0.5 on 2021-10-21 12:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_loginrecord'),
        ('Home', '0008_auto_20211021_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='action',
            new_name='raw_uri',
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=32)),
                ('url_path', models.CharField(max_length=128)),
                ('raw_uri', models.CharField(max_length=256)),
                ('login_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.LoginRecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
