# Generated by Django 3.0.5 on 2021-10-21 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20211021_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrecord',
            name='other_info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
