# Generated by Django 3.0.5 on 2021-10-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_accessrecord_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitlist',
            name='state',
            field=models.CharField(choices=[('see', 'see'), ('pass', 'pass'), ('try', 'try'), ('unknown', 'unknown'), ('save', 'save')], default='see', max_length=8),
        ),
    ]
