# Generated by Django 3.0.5 on 2021-11-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20211029_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlist',
            name='index',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
