# Generated by Django 3.0.5 on 2021-09-05 02:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestions',
            old_name='upTime',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='suggestions',
            old_name='status',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='suggestions',
            name='id',
        ),
        migrations.AddField(
            model_name='suggestions',
            name='deal_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestions',
            name='uid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='advise',
            field=models.CharField(max_length=512),
        ),
    ]
