# Generated by Django 3.0.5 on 2021-09-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestion', '0002_auto_20210905_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Helpless', 'Helpless')], default='Open', max_length=10),
        ),
    ]
