# Generated by Django 3.0.5 on 2021-10-29 03:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_loginrecord'),
        ('Home', '0012_accessrecord_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulateRecord',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('sim_code', models.TextField()),
                ('type', models.CharField(choices=[('save', 'save'), ('sim', 'sim')], default='save', max_length=8)),
                ('state', models.CharField(choices=[('success', 'success'), ('fail', 'fail')], default='fail', max_length=8)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('sim_result', models.TextField()),
                ('sim_result_url', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.TestList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
        ),
    ]
